# -*- coding: utf-8 -*-
"""Aggiunge/aggiorna la sezione 'dialoghi' (situazioni di tutti i giorni) in knowledge.json.
Idempotente: rilanciandolo riscrive la sezione con questi contenuti.

Ogni dialogo: id, icona, titolo (it), titoloRu, scena (descrizione), livello (1-2),
ruoli {A, B} (A = chi parla per primo), battute [{s: 'A'|'B', ru, it}],
parole [[ru, it], ...] (le espressioni chiave), nota (curiosità culturale, facoltativa).
"""
import json, io, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(HERE, "knowledge.json")


def dlg(id, icona, titolo, titoloRu, scena, livello, ruoli, battute, parole, nota=""):
    return {
        "id": id, "icona": icona, "titolo": titolo, "titoloRu": titoloRu, "scena": scena,
        "livello": livello, "ruoli": ruoli,
        "battute": [{"s": s, "ru": ru, "it": it} for s, ru, it in battute],
        "parole": [{"ru": ru, "it": it} for ru, it in parole],
        "nota": nota,
    }


dialoghi = [
    dlg("bar", "☕", "Al bar", "В кафе", "Ordini un cappuccino e un cornetto al bancone.", 1,
        {"A": "Бариста", "B": "Вы"},
        [
            ("A", "Здравствуйте! Что вы хотите?", "Buongiorno! Cosa desidera?"),
            ("B", "Здравствуйте. Один капучино, пожалуйста.", "Buongiorno. Un cappuccino, per favore."),
            ("A", "Большой или маленький?", "Grande o piccolo?"),
            ("B", "Маленький. И ещё круассан.", "Piccolo. E anche un cornetto."),
            ("A", "С собой или здесь?", "Da portare via o qui?"),
            ("B", "Здесь. Сколько с меня?", "Qui. Quanto le devo?"),
            ("A", "Триста двадцать рублей.", "Trecentoventi rubli."),
            ("B", "Можно картой?", "Posso pagare con la carta?"),
            ("A", "Конечно. Вот ваш кофе. Приятного аппетита!", "Certo. Ecco il suo caffè. Buon appetito!"),
            ("B", "Спасибо!", "Grazie!"),
        ],
        [("С собой", "da portare via"), ("Сколько с меня?", "quanto le devo?"), ("Можно картой?", "posso pagare con la carta?"),
         ("конечно", "certo"), ("Приятного аппетита!", "buon appetito!")],
        "In Russia il «кофе» è maschile anche se finisce in -е: si dice «мой кофе», non «моё кофе».",
    ),
    dlg("ristorante", "🍽️", "Al ristorante", "В ресторане", "Una cena in due: il cameriere consiglia le specialità russe.", 1,
        {"A": "Официант", "B": "Вы"},
        [
            ("A", "Добрый вечер! Вас сколько?", "Buonasera! Quanti siete?"),
            ("B", "Добрый вечер. Нас двое.", "Buonasera. Siamo in due."),
            ("A", "Пожалуйста, вот ваш столик. Вот меню.", "Prego, ecco il vostro tavolo. Ecco il menù."),
            ("B", "Спасибо. Что вы нам посоветуете?", "Grazie. Cosa ci consiglia?"),
            ("A", "Попробуйте борщ и пельмени. Это наши фирменные блюда.", "Provate il boršč e i pel'meni. Sono le nostre specialità."),
            ("B", "Хорошо. Два борща и одну порцию пельменей, пожалуйста.", "Va bene. Due boršč e una porzione di pel'meni, per favore."),
            ("A", "Что будете пить?", "Cosa prendete da bere?"),
            ("B", "Воду без газа и чай с лимоном.", "Acqua naturale e tè al limone."),
            ("A", "Отлично. Минуточку.", "Perfetto. Un attimo."),
            ("B", "Принесите, пожалуйста, счёт.", "Ci porti il conto, per favore."),
            ("A", "Конечно, сейчас.", "Certo, subito."),
        ],
        [("Нас двое.", "siamo in due"), ("столик", "tavolino (al ristorante)"), ("Что вы посоветуете?", "cosa consiglia?"),
         ("фирменное блюдо", "specialità della casa"), ("вода без газа", "acqua naturale"), ("счёт", "il conto")],
        "Il борщ è una zuppa di barbabietole, i пельмени sono ravioli di carne: due classici della cucina russa.",
    ),
    dlg("albergo", "🏨", "In albergo", "В гостинице", "Arrivi alla reception con una camera già prenotata.", 2,
        {"A": "Администратор", "B": "Вы"},
        [
            ("A", "Добрый день! Чем могу помочь?", "Buongiorno! Come posso aiutarla?"),
            ("B", "Добрый день. У меня забронирован номер. Моя фамилия Росси.", "Buongiorno. Ho una camera prenotata. Il mio cognome è Rossi."),
            ("A", "Минутку… Да, одноместный номер на три ночи. Ваш паспорт, пожалуйста.", "Un momento… Sì, una camera singola per tre notti. Il suo passaporto, per favore."),
            ("B", "Вот, пожалуйста.", "Ecco, prego."),
            ("A", "Спасибо. Ваш номер двести пятнадцать, на втором этаже. Вот ключ.", "Grazie. La sua camera è la 215, al primo piano. Ecco la chiave."),
            ("B", "Во сколько завтрак?", "A che ora è la colazione?"),
            ("A", "С семи до десяти утра.", "Dalle sette alle dieci di mattina."),
            ("B", "А здесь есть вай-фай?", "E qui c'è il wi-fi?"),
            ("A", "Да, пароль на карточке.", "Sì, la password è sul cartoncino."),
            ("B", "Спасибо большое!", "Grazie mille!"),
        ],
        [("Чем могу помочь?", "come posso aiutarla?"), ("забронирован номер", "camera prenotata"), ("одноместный номер", "camera singola"),
         ("ключ", "chiave"), ("завтрак", "colazione"), ("пароль", "password")],
        "In Russia il piano terra è il «первый этаж»: il «второй этаж» è il nostro primo piano.",
    ),
    dlg("strada", "🗺️", "Chiedere la strada", "Как пройти?", "Cerchi la Piazza Rossa e chiedi a un passante.", 1,
        {"A": "Вы", "B": "Прохожий"},
        [
            ("A", "Извините, вы не подскажете, как пройти к Красной площади?", "Mi scusi, sa dirmi come si arriva alla Piazza Rossa?"),
            ("B", "Идите прямо, потом налево.", "Vada dritto, poi a sinistra."),
            ("A", "Это далеко?", "È lontano?"),
            ("B", "Нет, недалеко. Минут десять пешком.", "No, non è lontano. Una decina di minuti a piedi."),
            ("A", "А где здесь метро?", "E dov'è la metro qui?"),
            ("B", "Метро направо, рядом с банком.", "La metro è a destra, vicino alla banca."),
            ("A", "Спасибо большое!", "Grazie mille!"),
            ("B", "Не за что.", "Di niente."),
        ],
        [("Как пройти к…?", "come si arriva a…?"), ("прямо", "dritto"), ("налево", "a sinistra"), ("направо", "a destra"),
         ("далеко / недалеко", "lontano / non lontano"), ("пешком", "a piedi"), ("Не за что.", "di niente")],
        "«Минут десять» con il numero dopo il nome vuol dire «circa dieci minuti»: l'ordine delle parole rende l'idea di approssimazione.",
    ),
    dlg("mercato", "🍎", "Al mercato", "На рынке", "Compri frutta e latte e chiedi i prezzi.", 1,
        {"A": "Продавец", "B": "Вы"},
        [
            ("A", "Здравствуйте! Что вам?", "Buongiorno! Cosa le serve?"),
            ("B", "Здравствуйте. Сколько стоят яблоки?", "Buongiorno. Quanto costano le mele?"),
            ("A", "Сто двадцать рублей за килограмм.", "Centoventi rubli al chilo."),
            ("B", "Дайте, пожалуйста, килограмм яблок и два банана.", "Mi dia, per favore, un chilo di mele e due banane."),
            ("A", "Что-нибудь ещё?", "Qualcos'altro?"),
            ("B", "Да, бутылку молока.", "Sì, una bottiglia di latte."),
            ("A", "Это всё?", "È tutto?"),
            ("B", "Да, всё. Сколько с меня?", "Sì, è tutto. Quanto le devo?"),
            ("A", "Двести девяносто рублей.", "Duecentonovanta rubli."),
            ("B", "Вот, пожалуйста.", "Ecco, prego."),
            ("A", "Ваша сдача. Всего доброго!", "Il suo resto. Buona giornata!"),
        ],
        [("Сколько стоит / стоят?", "quanto costa / costano?"), ("за килограмм", "al chilo"), ("Дайте, пожалуйста…", "mi dia, per favore…"),
         ("Что-нибудь ещё?", "qualcos'altro?"), ("сдача", "il resto"), ("Всего доброго!", "buona giornata! (congedo)")],
        "Dopo «килограмм» e «бутылка» il cibo va al genitivo: килограмм яблок, бутылка молока.",
    ),
    dlg("stazione", "🚆", "Alla stazione", "На вокзале", "Compri un biglietto del treno per San Pietroburgo.", 2,
        {"A": "Вы", "B": "Кассир"},
        [
            ("A", "Здравствуйте. Один билет до Санкт-Петербурга, пожалуйста.", "Buongiorno. Un biglietto per San Pietroburgo, per favore."),
            ("B", "На какое число?", "Per che data?"),
            ("A", "На завтра, на утро.", "Per domani mattina."),
            ("B", "Есть поезд в восемь тридцать.", "C'è un treno alle otto e trenta."),
            ("A", "Хорошо. Сколько стоит билет?", "Va bene. Quanto costa il biglietto?"),
            ("B", "Три тысячи пятьсот рублей.", "Tremilacinquecento rubli."),
            ("A", "С какой платформы отправляется поезд?", "Da quale binario parte il treno?"),
            ("B", "Это будет на табло. Приходите за двадцать минут.", "Sarà sul tabellone. Venga venti minuti prima."),
            ("A", "Спасибо!", "Grazie!"),
            ("B", "Счастливого пути!", "Buon viaggio!"),
        ],
        [("билет до…", "biglietto per…"), ("На какое число?", "per che data?"), ("поезд", "treno"), ("платформа", "binario"),
         ("табло", "tabellone"), ("Счастливого пути!", "buon viaggio!")],
        "Il treno veloce Mosca–San Pietroburgo si chiama «Сапсан» (falco pellegrino) e impiega circa quattro ore.",
    ),
    dlg("taxi", "🚕", "In taxi", "В такси", "Vai in aeroporto e hai un po' di fretta.", 2,
        {"A": "Водитель", "B": "Вы"},
        [
            ("A", "Добрый день! Куда едем?", "Buongiorno! Dove andiamo?"),
            ("B", "В аэропорт, пожалуйста.", "In aeroporto, per favore."),
            ("A", "Хорошо. Вы торопитесь?", "Va bene. Ha fretta?"),
            ("B", "Да, немного. Мой самолёт в шесть часов.", "Sì, un po'. Il mio aereo è alle sei."),
            ("A", "Не волнуйтесь, успеем.", "Non si preoccupi, facciamo in tempo."),
            ("B", "Сколько ехать?", "Quanto ci vuole?"),
            ("A", "Минут сорок, если нет пробок.", "Una quarantina di minuti, se non c'è traffico."),
            ("A", "Приехали!", "Siamo arrivati!"),
            ("B", "Спасибо. Сколько с меня?", "Grazie. Quanto le devo?"),
            ("A", "Тысяча двести.", "Milleduecento."),
            ("B", "Вот, пожалуйста. Сдачи не надо.", "Ecco a lei. Tenga il resto."),
        ],
        [("Куда едем?", "dove andiamo?"), ("торопиться", "avere fretta"), ("Не волнуйтесь.", "non si preoccupi"),
         ("Сколько ехать?", "quanto ci vuole (in macchina)?"), ("пробка", "ingorgo, traffico"), ("Сдачи не надо.", "tenga il resto")],
    ),
    dlg("farmacia", "💊", "In farmacia", "В аптеке", "Hai mal di testa e un po' di tosse.", 2,
        {"A": "Фармацевт", "B": "Вы"},
        [
            ("A", "Здравствуйте. Слушаю вас.", "Buongiorno. Mi dica."),
            ("B", "Здравствуйте. У меня болит голова. Что вы можете посоветовать?", "Buongiorno. Ho mal di testa. Cosa mi può consigliare?"),
            ("A", "Вот хорошее лекарство. Одна таблетка три раза в день после еды.", "Ecco un buon farmaco. Una compressa tre volte al giorno dopo i pasti."),
            ("B", "А у вас есть что-нибудь от кашля?", "E avete qualcosa per la tosse?"),
            ("A", "Да, есть сироп.", "Sì, c'è lo sciroppo."),
            ("B", "Хорошо, дайте, пожалуйста, и сироп тоже.", "Bene, mi dia anche lo sciroppo, per favore."),
            ("A", "С вас пятьсот сорок рублей. Выздоравливайте!", "Sono cinquecentoquaranta rubli. Guarisca presto!"),
            ("B", "Спасибо!", "Grazie!"),
        ],
        [("Слушаю вас.", "mi dica (lett. la ascolto)"), ("У меня болит голова.", "ho mal di testa"), ("лекарство", "medicina, farmaco"),
         ("таблетка", "compressa"), ("от кашля", "per la tosse"), ("Выздоравливайте!", "guarisca presto!")],
        "«У меня болит…» + la parte del corpo: болит голова (testa), болит горло (gola), болит живот (pancia).",
    ),
    dlg("conoscenza", "👋", "Fare conoscenza", "Знакомство", "A una festa Maša conosce Marco, un italiano.", 1,
        {"A": "Маша", "B": "Марко"},
        [
            ("A", "Привет! Я Маша. А тебя как зовут?", "Ciao! Io sono Maša. E tu come ti chiami?"),
            ("B", "Привет! Меня зовут Марко.", "Ciao! Mi chiamo Marco."),
            ("A", "Очень приятно. Ты откуда?", "Molto piacere. Di dove sei?"),
            ("B", "Я из Италии, из Рима. А ты?", "Sono italiano, di Roma. E tu?"),
            ("A", "Я из Москвы. Ты давно здесь?", "Io sono di Mosca. Sei qui da tanto?"),
            ("B", "Нет, только неделю. Я изучаю русский язык.", "No, solo da una settimana. Studio il russo."),
            ("A", "Ты хорошо говоришь по-русски!", "Parli bene il russo!"),
            ("B", "Спасибо, но я ещё говорю медленно.", "Grazie, ma parlo ancora lentamente."),
            ("A", "Ничего, это нормально. Кем ты работаешь?", "Non importa, è normale. Che lavoro fai?"),
            ("B", "Я архитектор. А ты?", "Sono architetto. E tu?"),
            ("A", "А я учительница.", "E io sono insegnante."),
        ],
        [("Ты откуда?", "di dove sei?"), ("Я из Италии.", "vengo dall'Italia"), ("давно", "da tanto tempo"),
         ("неделя", "settimana"), ("Кем ты работаешь?", "che lavoro fai?"), ("Ничего.", "non importa, niente")],
        "Con «из» il nome va al genitivo: из Италии, из Рима, из Москвы.",
    ),
    dlg("telefono", "📞", "Al telefono", "По телефону", "Paolo chiama Anja per invitarla al cinema.", 1,
        {"A": "Аня", "B": "Паоло"},
        [
            ("A", "Алло!", "Pronto!"),
            ("B", "Алло, Аня? Привет, это Паоло.", "Pronto, Anja? Ciao, sono Paolo."),
            ("A", "Привет, Паоло! Как дела?", "Ciao Paolo! Come va?"),
            ("B", "Хорошо, спасибо. Что ты делаешь в субботу?", "Bene, grazie. Cosa fai sabato?"),
            ("A", "Пока не знаю. А что?", "Ancora non lo so. Perché?"),
            ("B", "Давай пойдём в кино!", "Andiamo al cinema!"),
            ("A", "С удовольствием! Во сколько?", "Con piacere! A che ora?"),
            ("B", "В семь часов, у кинотеатра.", "Alle sette, davanti al cinema."),
            ("A", "Отлично. До субботы!", "Perfetto. A sabato!"),
            ("B", "Пока!", "Ciao!"),
        ],
        [("Алло!", "pronto! (al telefono)"), ("в субботу", "sabato"), ("пока не знаю", "ancora non lo so"),
         ("Давай пойдём…", "andiamo…"), ("С удовольствием!", "con piacere!"), ("Во сколько?", "a che ora?")],
        "Qui «пока» vuol dire «per ora»: «пока не знаю» = «per ora non lo so». In fondo al dialogo lo stesso «Пока!» è il saluto «ciao».",
    ),
    dlg("medico", "🩺", "Dal medico", "У врача", "Hai la febbre e mal di gola.", 2,
        {"A": "Врач", "B": "Вы"},
        [
            ("A", "Здравствуйте. Что вас беспокоит?", "Buongiorno. Cosa la disturba?"),
            ("B", "Здравствуйте, доктор. У меня высокая температура и болит горло.", "Buongiorno, dottore. Ho la febbre alta e mi fa male la gola."),
            ("A", "Давно?", "Da quanto tempo?"),
            ("B", "Два дня.", "Da due giorni."),
            ("A", "Откройте рот, пожалуйста… Да, горло красное. У вас простуда.", "Apra la bocca, per favore… Sì, la gola è rossa. Ha preso un raffreddore."),
            ("B", "Это серьёзно?", "È grave?"),
            ("A", "Нет, не волнуйтесь. Пейте много тёплого чая и отдыхайте.", "No, non si preoccupi. Beva molto tè caldo e si riposi."),
            ("B", "Спасибо, доктор.", "Grazie, dottore."),
            ("A", "Выздоравливайте!", "Guarisca presto!"),
        ],
        [("Что вас беспокоит?", "cosa la disturba?"), ("высокая температура", "febbre alta"), ("болит горло", "fa male la gola"),
         ("простуда", "raffreddore"), ("Это серьёзно?", "è grave?"), ("отдыхайте", "si riposi")],
    ),
    dlg("meteo", "🌦️", "Che tempo fa?", "Какая погода?", "Olja e Giulia parlano del freddo di Mosca.", 1,
        {"A": "Оля", "B": "Джулия"},
        [
            ("A", "Какая сегодня погода?", "Che tempo fa oggi?"),
            ("B", "Холодно! Минус десять.", "Fa freddo! Meno dieci."),
            ("A", "Правда? А вчера было тепло.", "Davvero? E ieri faceva caldo."),
            ("B", "Да, а завтра будет снег.", "Sì, e domani nevicherà."),
            ("A", "Я люблю зиму! А ты?", "Io amo l'inverno! E tu?"),
            ("B", "А я больше люблю лето. В Италии летом жарко и солнечно.", "Io preferisco l'estate. In Italia d'estate fa caldo e c'è il sole."),
            ("A", "Не забудь шапку и шарф!", "Non dimenticare il berretto e la sciarpa!"),
            ("B", "Хорошо, спасибо!", "Va bene, grazie!"),
        ],
        [("Какая погода?", "che tempo fa?"), ("холодно / тепло / жарко", "fa freddo / fa caldo (mite) / fa molto caldo"),
         ("снег", "neve"), ("зима / лето", "inverno / estate"), ("летом", "d'estate"), ("шапка, шарф", "berretto, sciarpa")],
        "Per il tempo il russo usa avverbi senza soggetto: «холодно» = «fa freddo», «было тепло» = «faceva caldo».",
    ),
    dlg("vestiti", "👕", "Comprare una giacca", "В магазине одежды", "Cerchi una giacca e chiedi un'altra taglia.", 2,
        {"A": "Продавец", "B": "Вы"},
        [
            ("A", "Здравствуйте! Вам помочь?", "Buongiorno! Posso aiutarla?"),
            ("B", "Да, я ищу куртку.", "Sì, cerco una giacca."),
            ("A", "Какой у вас размер?", "Che taglia porta?"),
            ("B", "Сорок восьмой.", "La quarantotto."),
            ("A", "Вот, посмотрите. Есть чёрная и синяя.", "Ecco, guardi. Ce n'è una nera e una blu."),
            ("B", "Можно примерить синюю?", "Posso provare quella blu?"),
            ("A", "Конечно. Примерочная там.", "Certo. Il camerino è là."),
            ("B", "Она мне немного мала. У вас есть размер побольше?", "Mi sta un po' piccola. Avete una taglia più grande?"),
            ("A", "Да, вот пятидесятый.", "Sì, ecco la cinquanta."),
            ("B", "Отлично, как раз! Я её беру.", "Perfetto, è giusta! La prendo."),
        ],
        [("Вам помочь?", "posso aiutarla?"), ("я ищу…", "cerco…"), ("размер", "taglia"), ("примерить", "provare (un vestito)"),
         ("примерочная", "camerino"), ("мала / велика", "piccola / grande (di taglia)"), ("как раз", "giusto, della misura giusta")],
    ),
    dlg("aeroporto", "✈️", "Controllo passaporti", "В аэропорту", "Arrivi a Mosca e passi il controllo di frontiera.", 2,
        {"A": "Пограничник", "B": "Вы"},
        [
            ("A", "Добрый день. Ваш паспорт, пожалуйста.", "Buongiorno. Il suo passaporto, per favore."),
            ("B", "Вот, пожалуйста.", "Ecco, prego."),
            ("A", "Цель вашего визита?", "Scopo della visita?"),
            ("B", "Туризм.", "Turismo."),
            ("A", "Сколько дней вы будете в России?", "Quanti giorni resterà in Russia?"),
            ("B", "Десять дней.", "Dieci giorni."),
            ("A", "Где вы будете жить?", "Dove alloggerà?"),
            ("B", "В гостинице в центре Москвы.", "In un albergo nel centro di Mosca."),
            ("A", "Хорошо. Добро пожаловать в Россию!", "Bene. Benvenuto in Russia!"),
            ("B", "Спасибо!", "Grazie!"),
        ],
        [("паспорт", "passaporto"), ("Цель визита?", "scopo della visita?"), ("туризм", "turismo"),
         ("Где вы будете жить?", "dove alloggerà?"), ("в центре", "in centro"), ("Добро пожаловать!", "benvenuto!")],
    ),
    dlg("ospiti", "🏠", "Ospiti a cena", "В гостях", "Natascia ti invita a cena a casa sua.", 1,
        {"A": "Наташа", "B": "Вы"},
        [
            ("A", "Добро пожаловать! Проходите, пожалуйста.", "Benvenuto! Prego, entri."),
            ("B", "Спасибо за приглашение! Это вам.", "Grazie per l'invito! Questo è per lei."),
            ("A", "Ой, какие красивые цветы! Спасибо!", "Oh, che bei fiori! Grazie!"),
            ("A", "Садитесь за стол. Угощайтесь!", "Si accomodi a tavola. Si serva pure!"),
            ("B", "Как вкусно! Что это?", "Che buono! Cos'è?"),
            ("A", "Это салат «Оливье». Хотите ещё?", "È l'insalata Olivier. Ne vuole ancora?"),
            ("B", "Да, с удовольствием.", "Sì, con piacere."),
            ("A", "А теперь чай с тортом.", "E adesso tè con la torta."),
            ("B", "Спасибо, всё было очень вкусно!", "Grazie, era tutto buonissimo!"),
        ],
        [("Проходите!", "entri, prego!"), ("Спасибо за приглашение!", "grazie per l'invito!"), ("Это вам.", "questo è per lei"),
         ("Угощайтесь!", "si serva!"), ("Как вкусно!", "che buono!"), ("с удовольствием", "con piacere")],
        "In Russia i fiori si regalano in numero dispari: i mazzi con un numero pari si portano ai funerali.",
    ),
    dlg("museo", "🎟️", "Al museo", "В музее", "Compri i biglietti e chiedi le regole del museo.", 2,
        {"A": "Вы", "B": "Кассир"},
        [
            ("A", "Здравствуйте! Два билета, пожалуйста.", "Buongiorno! Due biglietti, per favore."),
            ("B", "Взрослые?", "Adulti?"),
            ("A", "Один взрослый и один студенческий. Вот студенческий билет.", "Uno intero e uno per studenti. Ecco la tessera universitaria."),
            ("B", "С вас семьсот рублей.", "Sono settecento rubli."),
            ("A", "Во сколько закрывается музей?", "A che ora chiude il museo?"),
            ("B", "В шесть часов вечера.", "Alle sei di sera."),
            ("A", "Здесь можно фотографировать?", "Qui si possono fare foto?"),
            ("B", "Можно, но без вспышки.", "Sì, ma senza flash."),
            ("A", "Спасибо! А где гардероб?", "Grazie! E dov'è il guardaroba?"),
            ("B", "Внизу, направо.", "Di sotto, a destra."),
        ],
        [("взрослый", "adulto"), ("студенческий билет", "tessera universitaria"), ("Во сколько закрывается…?", "a che ora chiude…?"),
         ("можно / нельзя", "si può / non si può"), ("без вспышки", "senza flash"), ("гардероб", "guardaroba")],
        "Nei musei e nei teatri russi il cappotto non si porta dentro: si lascia sempre al «гардероб».",
    ),
]

with io.open(PATH, "r", encoding="utf-8") as f:
    d = json.load(f)

d["dialoghi"] = dialoghi
note = d["meta"].get("note", "")
if "dialoghi" not in note:
    d["meta"]["note"] = note + " Sezione 'dialoghi' = situazioni di tutti i giorni da ascoltare e recitare (scripts/add_dialoghi.py)."

with io.open(PATH, "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=False, indent=2)

print("OK: dialoghi =", len(dialoghi), "| battute =", sum(len(x["battute"]) for x in dialoghi))
